# site settings

title: Vadim Zendejas
description: Vadim Zendejas Home Page
taglong: Global Technology Leader <br> Board Advisor | Value Investor
tagshort: Global Technology Leader
domain: vadimzendejas.com
url: https://vadimzendejas.com
baseurl: ""
permalink: pretty
repo: https://github.com/vadimzendejas/vadimzendejas.github.io

# author settings

author:
  name: Vadim Zendejas
photo: /assets/photo.png

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-github-metadata

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

tag_page_layout: tag
tag_page_dir: tags

google_analytics: G-MG6KWMXXM6

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
